defines.h: Add openbsd-compat define for CLOCK_REALTIME
MacOS 10.10 does not implement clock_gettime(), and so is missing the defines
for CLOCK_REALTIME and CLOCK_MONOTONIC. A definition exists for CLOCK_MONOTONIC
in openbsd-compat , but CLOCK_REALTIME was missing.

    ../../smtpd/queue_fs.c:763:20: error: use of undeclared identifier 'CLOCK_REALTIME'
            if (clock_gettime(CLOCK_REALTIME, &startup))
                              ^
    1 error generated.
    make[3]: *** [../../smtpd/smtpd-queue_fs.o] Error 1